const countries = [
  "Afghanistan",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belgium",
  "Benin",
  "Brunei Darussalam",
  "Cambodia",
  "Canada",
  "China",
  "Cyprus",
  "Democratic Republic of the Congo",
  "Denmark",
  "Egypt",
  "Estonia",
  "Finland",
  "France",
  "France, Metropolitan",
  "Gabon",
  "Georgia",
  "Germany",
  "Hong Kong",
  "Hungary",
  "India",
  "Ireland",
  "Italy",
  "Japan",
  "Korea (South)",
  "Kuwait",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mauritius",
  "Mozambique",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Oman",
  "Pakistan",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Russian Federation",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Turkey",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
];
// .toLowerCase().replace(/ /g, "-")
export const countryOptions = countries.map((country) => (
  <option key={country} value={country}>
    {country}
  </option>
));
