const occupations = [
  "Accounting",
  "Architect",
  "Army officer",
  "BA",
  "BCS Cadre",
  "BSC",
  "Banker",
  "Barrister",
  "Business",
  "Buying House Job",
  "Chartered Accountant",
  "Computer Professional",
  "Consultant",
  "Customer Call Centre",
  "Defense Officer",
  "Dentist",
  "Designer",
  "Doctor",
  "Engineer",
  "Fazel",
  "Freelancer",
  "Govt. Service Holder",
  "Hafiz",
  "Homemaker",
  "Industrialist",
  "Journalist",
  "Lawyer",
  "Lecturer",
  "MA",
  "MSC",
  "Marine Engineer",
  "Media Person",
  "Navy officer",
  "News Presenter",
  "Nurse",
  "Owner",
  "Pharmacist",
  "Photographer",
  "Police officer",
  "Private Service Holder",
  "Professor",
  "Religious Institution",
  "Sailor",
  "Self Employed",
  "Social Worker",
  "Sports",
  "Student",
  "Supermarkets",
  "Teacher",
  "Telecommunication",
  "Unemployed",
  "Writer",
  "Other",
];
// .toLowerCase().replace(/ /g, "-")
export const professionOptions = occupations.map((occupation) => (
  <option key={occupation} value={occupation}>
    {occupation}
  </option>
));
